name: Verifica DO e notifica com parâmetros
on:
  workflow_dispatch:
    inputs:
      text:
        type: string
        description: 'Texto a ser pesquisado no DO'
        required: true
      date:
        type: string
        description: 'Em qual data pesquisar'
        required: true

jobs:
  verifica-do-manual-sem-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Instala dependencias
        run: pip install -r requirements.txt
      - name: Roda o script e notifica caso encontrar alguma coisa
        run: ./src/main.py '${{ github.event.inputs.text }}' --pushover_user ${PUSHOVER_USER_KEY} --pushover_api ${PUSHOVER_API_KEY}
        env: # Ou como uma variável de ambiente
          PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
